// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package app

import (
	"time"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
